// Generated by Landing Page Scaffolder — 2026-03-16
// Stack: Next.js 14+ App Router, React, Tailwind CSS
// Design style: bold-startup

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sell Your House Fast for Cash | Heberer Homes",
  description: "Heberer Homes buys houses in any condition for cash. No repairs, no agents, no fees. Get a fair cash offer in 24 hours and close in as little as 7 days.",
  openGraph: {
    title: "Sell Your House Fast for Cash | Heberer Homes",
    description: "Heberer Homes buys houses in any condition for cash. No repairs, no agents, no fees. Get a fair cash offer in 24 hours and close in as little as 7 days.",
    type: "website",
  },
};

function Navbar() {
  return (
    <nav className="sticky top-0 z-50 bg-white border-b border-gray-200 backdrop-blur-sm">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
        <a href="#" className="text-xl font-bold text-gray-900">Heberer Homes</a>
        <div className="hidden items-center gap-8 md:flex">
          <a href="#how-it-works" className="text-gray-500 hover:text-gray-900 font-medium transition-colors">How It Works</a>
          <a href="#why-us" className="text-gray-500 hover:text-gray-900 font-medium transition-colors">Why Us</a>
          <a href="#testimonials" className="text-gray-500 hover:text-gray-900 font-medium transition-colors">Testimonials</a>
          <a href="#faq" className="text-gray-500 hover:text-gray-900 font-medium transition-colors">FAQ</a>
          <a href="#get-offer" className="rounded-lg bg-orange-500 hover:bg-orange-600 text-white px-5 py-2.5 text-sm font-semibold transition-colors">
            Get My Cash Offer
          </a>
        </div>
      </div>
    </nav>
  );
}

function Hero() {
  return (
    <section className="flex min-h-[80vh] flex-col items-center justify-center px-6 py-24 text-center bg-white">
      <div className="mx-auto max-w-4xl">
        <h1 className="mb-6 text-5xl font-bold tracking-tight text-gray-900 md:text-7xl">
          Sell Your House Fast — For Cash. No Repairs. No Hassle.
        </h1>
        <p className="mx-auto mb-10 max-w-2xl text-xl text-gray-500">
          Heberer Homes buys houses in any condition. Get a fair, no-obligation cash offer within 24 hours and close on your timeline — as fast as 7 days. No agents, no commissions, no hidden fees.
        </p>
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
          <a href="#get-offer" className="rounded-lg bg-orange-500 hover:bg-orange-600 text-white px-8 py-3 text-lg font-semibold transition-colors">
            Get My Free Cash Offer
          </a>
          <a href="tel:5551234567" className="rounded-lg border-2 border-orange-500 text-orange-600 hover:bg-orange-50 px-8 py-3 text-lg font-semibold transition-colors">
            Call Us Now: (555) 123-4567
          </a>
        </div>
      </div>
    </section>
  );
}

function Features() {
  return (
    <section className="bg-orange-50/30 px-6 py-24">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-4 text-center text-4xl font-bold text-gray-900">How It Works</h2>
        <p className="mx-auto mb-16 max-w-2xl text-center text-lg text-gray-500">Selling your house shouldn't take months or cost thousands in repairs and agent fees. With Heberer Homes, it takes 3 simple steps.</p>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        <div className="shadow-xl rounded-3xl bg-white rounded-xl p-8">
          <div className="mb-4 text-3xl">1</div>
          <h3 className="mb-3 text-xl font-semibold text-gray-900">Tell Us About Your Property</h3>
          <p className="text-gray-500">Fill out our simple form or give us a call. Tell us about your house — any condition, any situation. We buy homes others won't.</p>
        </div>
        <div className="shadow-xl rounded-3xl bg-white rounded-xl p-8">
          <div className="mb-4 text-3xl">2</div>
          <h3 className="mb-3 text-xl font-semibold text-gray-900">Get Your Fair Cash Offer</h3>
          <p className="text-gray-500">We'll evaluate your property and present a no-obligation cash offer within 24 hours. No lowball tactics — just a fair, honest price.</p>
        </div>
        <div className="shadow-xl rounded-3xl bg-white rounded-xl p-8">
          <div className="mb-4 text-3xl">3</div>
          <h3 className="mb-3 text-xl font-semibold text-gray-900">Close On Your Timeline</h3>
          <p className="text-gray-500">Pick your closing date — as soon as 7 days or whenever works for you. We handle all the paperwork and pay all closing costs. Walk away with cash in hand.</p>
        </div>
        </div>
      </div>
    </section>
  );
}

function Testimonials() {
  return (
    <section className="px-6 py-24 bg-white">
      <div className="mx-auto max-w-7xl">
        <h2 className="mb-16 text-center text-4xl font-bold text-gray-900">Homeowners Who Trusted Heberer Homes</h2>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-xl border border-gray-200 p-8">
          <p className="mb-6 text-lg italic text-gray-500">"I inherited a house that needed $40K in repairs. Heberer Homes gave me a fair offer and closed in 10 days. No contractors, no stress, no surprises. I couldn't believe how easy it was."</p>
          <div>
            <p className="font-semibold text-gray-900">Sarah M.</p>
            <p className="text-sm text-gray-500">Inherited Property, Louisville, KY</p>
          </div>
        </div>
        <div className="rounded-xl border border-gray-200 p-8">
          <p className="mb-6 text-lg italic text-gray-500">"After my divorce, I needed to sell fast and move on. They made me an offer the same day I called and worked around my schedule. The whole process was respectful and professional."</p>
          <div>
            <p className="font-semibold text-gray-900">James T.</p>
            <p className="text-sm text-gray-500">Divorce Sale, Lexington, KY</p>
          </div>
        </div>
        <div className="rounded-xl border border-gray-200 p-8">
          <p className="mb-6 text-lg italic text-gray-500">"We were facing foreclosure and running out of time. Heberer Homes stepped in, made a fair cash offer, and closed in just 8 days. They literally saved our credit and gave us a fresh start."</p>
          <div>
            <p className="font-semibold text-gray-900">Linda & Robert K.</p>
            <p className="text-sm text-gray-500">Foreclosure Prevention, Cincinnati, OH</p>
          </div>
        </div>
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section className="bg-orange-600 px-6 py-24 text-center text-white">
      <div className="mx-auto max-w-3xl">
        <h2 className="mb-4 text-4xl font-bold">Ready to Sell Your House the Easy Way?</h2>
        <p className="mb-10 text-xl opacity-90">No repairs. No agents. No fees. Just a fair cash offer and a closing date that works for you. Get started in under 60 seconds.</p>
        <a href="#get-offer" className="rounded-lg bg-white px-8 py-3 text-lg font-semibold text-orange-600 transition-colors hover:bg-gray-100">
          Get My Free Cash Offer Now
        </a>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-gray-200 bg-white px-6 py-10 text-center text-gray-500">
      <p>&copy; 2026 Heberer Homes. All rights reserved. | We buy houses in any condition for cash.</p>
    </footer>
  );
}

export default function LandingPage() {
  return (
    <main>
      <Navbar />
      <Hero />
      <Features />
      <Testimonials />
      <CTASection />
      <Footer />
    </main>
  );
}
